---
title: Control Estadístico de Calidad (Entrega 1)
authors:
  - name: Michel Mendivenson Barragán Zabala
    department: Departamento de Estadística
    affiliation: Universidad Nacional de Colombia
    email: mbarraganz@unal.edu.co
  - name: Juan Sebastián Huertas Pirajan
    department: Departamento de Estadística
    affiliation: Universidad Nacional de Colombia
    email: juhuertasp@unal.edu.co
  - name: Diego Andres Paez Molina
    department: Departamento de Estadística
    affiliation: Universidad Nacional de Colombia
    email: dpaezm@unal.edu.co
output: 
  rticles::arxiv_article
header-includes:
  # La siguiente línea es para eliminar el enumerado de las secciones declaradas con ##
  - \setcounter{secnumdepth}{0}
  # La siguiente línea es para eliminar el título del abstract
  - \renewenvironment{abstract}{}{}
  - \renewcommand{\theenumi}{\alph{enumi}}
---

## Ejercicio 1

Sea $X \sim N(\mu, \sigma)$ una característica de calidad. Mediante simulaciones Mediante simulaciones, establezca el comportamiento del *ARL* (en control y fuera de él) de las Cartas $R$ y $S$ para observaciones normales con límites $3\sigma$ y muestras de tamaño (a) $n = 3$ y (b) $n = 10$ ¿Qué regularidades observa?

> Para la implementación de la solución, se creará en R una función que nos permita simular cuantás veces querramos el momento en un proceso da una alerta (bien sea verdadera o falsa) con argumentos que nos permitan modificar tanto el tamaño de muestra $n$ como los límites de la carta de control y su línea central. La función se define como sigue:



> Los resultados para diferentes corrimientos de la línea central se encuentran condensados en la tabla a continuación:

> Como podemos observar $\cdots$


## Ejercicio 2

Sea $X \sim N(\mu, \sigma)$ una característica de calidad. Se sabe que los valores objetivo de los parámetros del proceso son $\mu = \mu_0$ y $\sigma = \sigma_0$. Construir las curvas OC de la carta $S^2$ con límites de probabilidad. Interpretar los resultados

## Ejercicio 3

Sea $X \sim N(\mu_0, \sigma_0)$ una característica de calidad. Construya la carta $\bar{X}$ para el monitoreo de la media del proceso. Genere 10 muestras de tamaño $n$ provenientes de $X$, de tal modo que la media muestral de ninguna de ellas caiga fuera de los límites de control. A partir del undécimo momento de monitoreo se pide generar muestras del mismo tamaño $n$ provenientes de una distribución normal con media $\mu_1 = \mu_0 + k\sigma_0$ y $\sigma_1 = \sigma_0$ (con $k = 1,0$) hasta que la carta emita una señal por primera vez. Si se asume que el proceso caracterizado por $X$ es estable y que se desconoce el momento en el cual se produjo el incremento en el nivel medio, ¿en qué muestra ocurrió el cambio en la media del proceso más probablemente?

## Ejercicio 4

Sea $X \sim N(\mu_0, \sigma_0)$ una característica de calidad. Se pide:  
\begin{enumerate}
  \item Mediante simulaciones, establezca el comportamiento del ARL de la Carta $\bar{X}$ con límites tres sigma para observaciones normales.
  \item Genere 20 subgrupos racionales de tamaño $n = 3$ provenientes de $X$. Asúmase que el proceso es estable en cuanto a dispersión y con los subgrupos iniciales, construya la carta $\bar{X}$ como es habitual hasta verificar la estabilidad del proceso. Establezca el comportamiento del ARL para la carta que se obtiene del análisis de Fase I realizado.
  \item Repetir lo indicado en el literal (b) con 50 subgrupos racionales de tamaño $n = 3$. Comente los resultados.
\end{enumerate}

## Ejercicio 5

Calcular el ARL de la Carta $\bar{X}$ mediante cadenas de Markov. Diseñar la carta con límites de control ubicados a tres desviaciones estándar de la media y dividiendo la región de control estadístico en franjas de ancho igual a una desviación estándar.